name: movies_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  bloc: ^8.1.4
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.4.3+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_bloc: ^8.1.5
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  iconly: ^1.0.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  lottie: ^3.3.1
  material_design_icons_flutter: ^7.0.7296
  photo_view: ^0.15.0
  responsive_navigation_bar: ^5.0.2
  retrofit: ^4.1.0
  shimmer: ^3.0.0
  skeletonizer: ^2.1.0+1
  timeago: ^3.6.1
  url_launcher: ^6.3.0
  youtube_player_flutter: ^9.0.1

dev_dependencies:
  build_runner: ^2.4.10

  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  hive_generator: ^2.0.1
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0

# --- الحل هنا ---
# هذا القسم يجبر كل الحزم على استخدام إصدارات محددة لحل التعارض
dependency_overrides:
  analyzer: ^6.5.0
  build_resolvers: ^2.4.2
  dart_style: ^2.3.6

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
