name: movies_app
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
dependencies:
  bloc: ^9.0.0
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.3.1
  dio: ^5.9.0
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  font_awesome_flutter: ^10.9.0
  freezed: ^3.2.0
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  iconly: ^1.0.1
  image_filter_pro: ^0.1.11
  json_annotation: ^4.9.0
  material_design_icons_flutter: ^7.0.7296
  responsive_navigation_bar: ^5.0.2
  retrofit: ^4.7.1
  retrofit_generator: ^10.0.2
  skeletonizer: ^2.1.0+1
  timeago: ^3.7.1
  url_launcher: ^6.3.2
  youtube_player_flutter: ^9.1.2

dev_dependencies:
  build_runner: ^2.6.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.10.0

flutter:

  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/
  #   - images/a_dot_ham.jpeg
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
