name: movies_app
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Core & State Management
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  equatable: ^2.0.5
  dartz: ^0.10.1

  # Networking & API
  dio: ^5.4.3+1
  retrofit: ^4.1.0
  
  # Data Persistence
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI & UX
  cupertino_icons: ^1.0.8
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  iconly: ^1.0.1
  skeletonizer: ^1.0.1
  youtube_player_flutter: ^9.0.1
  intl: ^0.20.2
  
  # Utilities
  url_launcher: ^6.3.0
  timeago: ^3.6.1
  
  # Code Generation (Annotations)
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Development Tools
  device_preview: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

  # Code Generation (Builders)
  build_runner: ^2.4.10
  freezed: ^2.5.2
  retrofit_generator: ^8.1.0
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1

# --- الحل هنا ---
# هذا القسم يجبر كل الحزم على استخدام إصدارات محددة لحل التعارض
dependency_overrides:
  analyzer: '6.4.1'
  meta: '1.15.0'

flutter:
  uses-material-design: true

  assets:
    - assets/animations/
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
